# データ分析入門

## 第３章 確率の初歩

### パッケージ読み込み

In [1]:
# !pip install japanize_matplotlib
# !pip install sympy

%matplotlib inline
import japanize_matplotlib
from matplotlib import pyplot as plt

import pandas as pd
from pathlib import Path
import numpy as np

import sympy as sy


### 確率の計算 (loop)

In [4]:
(1 % 2) ==0,(2 % 2) ==0

(False, True)

In [5]:
(1 % 2) !=0,(2 % 2) !=0

(True, False)

In [31]:
1/3

0.3333333333333333

In [10]:
sy.Rational(1,3)

1/3

In [11]:
sy.Rational(2,4)

1/2

In [30]:
r_2=0
r_even=0
r_odd=0
totalN=0
print(list(range(1,4)))

for i in range(1,4):
    for j in range(1,4):
        totalN=totalN+1
        if ((i+j) %2)==0:
            r_even=r_even+1
        else:
            r_odd=r_odd+1
        if (i+j)==2:
            r_2=r_2+1
        
print(f'合計が偶数である確率は {sy.Rational(r_even,totalN)}')
print(f'合計が奇数である確率は {sy.Rational(r_odd,totalN)}')
print(f'合計が2である確率は      {sy.Rational(r_2,totalN)}')

[1, 2, 3]
合計が偶数である確率は 5/9
合計が奇数である確率は 4/9
合計が2である確率は      1/9


In [32]:
list(range(4))

[0, 1, 2, 3]

In [26]:
print(list(range(1,4)))

[1, 2, 3]


### 確率の計算 (numpy)

In [32]:
np.arange(1,4)

array([1, 2, 3])

In [5]:
list(range(1,4))*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [12]:
sum([[i]*3 for i in range(1,4)],[])

[1, 1, 1, 2, 2, 2, 3, 3, 3]

In [13]:
np.stack([[1,1],[2,2]])

array([[1, 1],
       [2, 2]])

In [2]:
L1=list(range(1,4))*3
L2=sum([[i]*3 for i in range(1,4)],[])
L3=np.stack([L1,L2])
print(L3)

print(f'{np.where(sum(L3)==2)[0]},{np.where((sum(L3) % 2)==0)[0]},{np.where((sum(L3) % 2)!=0)[0]}')

r_2=len(np.where(sum(L3)==2)[0])
r_even=len(np.where((sum(L3) % 2)==0)[0])
r_odd=len(np.where((sum(L3) % 2)!=0)[0])
totalN=len(L1)

print(f'合計が偶数である確率は {sy.Rational(r_even,totalN)}')
print(f'合計が奇数である確率は {sy.Rational(r_odd,totalN)}')
print(f'合計が2である確率は      {sy.Rational(r_2,totalN)}')

[[1 2 3 1 2 3 1 2 3]
 [1 1 1 2 2 2 3 3 3]]
[0],[0 2 4 6 8],[1 3 5 7]
合計が偶数である確率は 5/9
合計が奇数である確率は 4/9
合計が2である確率は      1/9


In [30]:
(np.where((sum(L3) % 2)==0))

(array([0, 2, 4, 6, 8]),)

In [7]:
np.where(sum(L3)==2)

(array([0]),)

In [4]:
len(np.where(sum(L3)==2))

1