# データ分析入門

## 第４章 条件付き確率

### パッケージ読み込み

In [1]:
# !pip install japanize_matplotlib
# !pip install sympy

%matplotlib inline
import japanize_matplotlib
from matplotlib import pyplot as plt

import pandas as pd
from pathlib import Path
import numpy as np

import sympy as sy


### 確率の計算 (loop)

In [4]:
(1 % 2) ==0,(2 % 2) ==0

(False, True)

In [5]:
(1 % 2) !=0,(2 % 2) !=0

(True, False)

In [31]:
1/3

0.3333333333333333

In [10]:
sy.Rational(1,3)

1/3

In [11]:
sy.Rational(2,4)

1/2

In [3]:
with5=0
with5_not=0
sum7=0
totalN=0
print(list(range(1,7)))

for i in range(1,7):
    for j in range(1,7):
        totalN=totalN+1
        if (i==5) or (j==5):
            with5=with5+1
        else:
            with5_not=with5_not+1
        if (i+j)==7:
            sum7=sum7+1
        
print(f'どちらかが５になる確率は {sy.Rational(with5,totalN)}')
print(f'どちらかが５にならない確率は {sy.Rational(with5_not,totalN)}')
print(f'合計が7である確率は      {sy.Rational(sum7,totalN)}')

[1, 2, 3, 4, 5, 6]
どちらかが５になる確率は 11/36
どちらかが５にならない確率は 25/36
合計が7である確率は      1/6


In [32]:
list(range(4))

[0, 1, 2, 3]

In [26]:
print(list(range(1,4)))

[1, 2, 3]


### 確率の計算 (numpy)

In [32]:
np.arange(1,4)

array([1, 2, 3])

In [5]:
list(range(1,4))*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [12]:
sum([[i]*3 for i in range(1,4)],[])

[1, 1, 1, 2, 2, 2, 3, 3, 3]

In [13]:
np.stack([[1,1],[2,2]])

array([[1, 1],
       [2, 2]])

In [12]:
L1

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4,
       5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [30]:
np.where(np.logical_not((L1==5) |(L2==5)))

(array([ 0,  1,  2,  3,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 17, 18, 19,
        20, 21, 23, 30, 31, 32, 33, 35]),)

In [ ]:
# http://ailaby.com/logical_and/
np.logical_not(x)        # not x  と同じ
np.logical_and(x, y)     # x and y または x & y  と同じ
np.logical_or(x, y)      # x or y または x | y  と同じ
np.logical_xor(x, y)     # x ^ y  と同じ

In [37]:
NofD=6
L1=np.array(list(range(1,NofD+1))*NofD)
L2=np.array(sum([[i]*NofD for i in range(1,NofD+1)],[]))
L3=np.stack([L1,L2])
print(L3)

print(f'{np.where(sum(L3)==7)[0]},{np.where((L1==5) |(L2==5))[0]},{np.where(np.logical_not((L1==5) |(L2==5)))[0]}')

sum7=len(np.where(sum(L3)==7)[0])
with5=len(np.where((L1==5) |(L2==5))[0])
with5_not=len(np.where(np.logical_not((L1==5) |(L2==5)))[0])
totalN=len(L1)

print(f'どちらかが５になる確率は {sy.Rational(with5,totalN)}')
print(f'どちらかが５にならない確率は {sy.Rational(with5_not,totalN)}')
print(f'合計が7である確率は      {sy.Rational(sum7,totalN)}')

[[1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6]
 [1 1 1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4 5 5 5 5 5 5 6 6 6 6 6 6]]
[ 5 10 15 20 25 30],[ 4 10 16 22 24 25 26 27 28 29 34],[ 0  1  2  3  5  6  7  8  9 11 12 13 14 15 17 18 19 20 21 23 30 31 32 33
 35]
どちらかが５になる確率は 11/36
どちらかが５にならない確率は 25/36
合計が7である確率は      1/6


In [38]:
# https://note.nkmk.me/python-numpy-condition/

# numpy.all(): すべての要素が条件を満たす行・列を抽出
# numpy.any(): 条件を満たす要素が一つでもある行・列を抽出

In [7]:
np.where(sum(L3)==2)

(array([0]),)

In [4]:
len(np.where(sum(L3)==2))

1