In [ ]:
## Python basics for novice data scientists, supported by Wagatsuma Lab@Kyutech 
#
# The MIT License (MIT): Copyright (c) 2020 Hiroaki Wagatsuma and Wagatsuma Lab@Kyutech
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. */
#
# # @Time    : 2020-6-18 
# # @Author  : Hiroaki Wagatsuma
# # @Site    : https://github.com/hirowgit/2A_python_basic_course
# # @IDE     : Python 3.10.9 (main, Dec 15 2022, 18:18:30) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
# # @File    : ksp_novice_lec01.py 

In [5]:
import numpy as np
import numpy.matlib
import os
import sys
import codecs
import matplotlib.pyplot as plt
import pandas as pd
from openpyxl import Workbook
import pprint

## Example 1

In [6]:
a=[0,1,2,3,4,5,6,7,8,9]

In [7]:
display(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [9]:
a_np=np.array(a)

In [7]:
display(a_np)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
print(a_np)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
np.sum(a_np)

45

In [27]:
sum(a)

45

## Example 2

In [11]:
A=[[1,4,7],[2,5,8],[3,6,9]]

In [13]:
print(A)

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]


In [14]:
sum(A[0])

12

In [23]:
A=np.array([[1,4,7],[2,5,8],[3,6,9]])

In [22]:
print(A_np)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [24]:
np.sum(A[0,:])

12

In [25]:
np.sum(A[:,0])

6

In [26]:
np.sum(A)

45

## Example 3

In [60]:
np.random.randint(1, 7, (2,2))

array([[6, 1],
       [2, 2]])

In [61]:
index=np.random.randint(1, 10, (18,1))
display(index)

array([[2],
       [4],
       [3],
       [8],
       [9],
       [9],
       [5],
       [5],
       [2],
       [7],
       [8],
       [9],
       [7],
       [4],
       [9],
       [7],
       [1],
       [3]])

In [65]:
score=np.random.randint(0, 100, (18,1))
display(score)

array([[98],
       [80],
       [88],
       [37],
       [93],
       [99],
       [72],
       [ 6],
       [88],
       [86],
       [25],
       [25],
       [57],
       [59],
       [88],
       [56],
       [49],
       [39]])

In [66]:
B=np.hstack([index,score])
display(B)

array([[ 2, 98],
       [ 4, 80],
       [ 3, 88],
       [ 8, 37],
       [ 9, 93],
       [ 9, 99],
       [ 5, 72],
       [ 5,  6],
       [ 2, 88],
       [ 7, 86],
       [ 8, 25],
       [ 9, 25],
       [ 7, 57],
       [ 4, 59],
       [ 9, 88],
       [ 7, 56],
       [ 1, 49],
       [ 3, 39]])

In [67]:
index_sum=np.sum(B[:,0])
score_sum=np.sum(B[:,1])
display(index_sum)
display(score_sum)

102

1145

In [68]:
index

array([[2],
       [4],
       [3],
       [8],
       [9],
       [9],
       [5],
       [5],
       [2],
       [7],
       [8],
       [9],
       [7],
       [4],
       [9],
       [7],
       [1],
       [3]])

In [70]:
index1=np.where(index<5)[0]
index1

array([ 0,  1,  2,  8, 13, 16, 17])

In [72]:
score

array([[98],
       [80],
       [88],
       [37],
       [93],
       [99],
       [72],
       [ 6],
       [88],
       [86],
       [25],
       [25],
       [57],
       [59],
       [88],
       [56],
       [49],
       [39]])

In [71]:
score[index1]

array([[98],
       [80],
       [88],
       [88],
       [59],
       [49],
       [39]])

In [73]:
index1=np.where(index<5)[0]
display(index1)

value_less_than_five=score[index1]
display(value_less_than_five)
sum_value1=np.sum(value_less_than_five)
display(sum_value1)


array([ 0,  1,  2,  8, 13, 16, 17])

array([[98],
       [80],
       [88],
       [88],
       [59],
       [49],
       [39]])

501

In [74]:
index2=np.where(index>=5)[0]
display(index2)
value_five_or_more=score[index2]
display(value_five_or_more)
sum_value2=np.sum(value_five_or_more)
display(sum_value2)

array([ 3,  4,  5,  6,  7,  9, 10, 11, 12, 14, 15])

array([[37],
       [93],
       [99],
       [72],
       [ 6],
       [86],
       [25],
       [25],
       [57],
       [88],
       [56]])

644

In [75]:
sum_all=sum_value1+sum_value2
display(sum_all)

1145

## ----------------- Summary-----------------

In [46]:
index=np.random.randint(1, 10, (18,1))
score=np.random.randint(0, 100, (18,1))
B=np.hstack([index,score])
index_sum=np.sum(B[:,0])
score_sum=np.sum(B[:,1])

index1=np.where(index<5)[0]
value_less_than_five=score[index1]
sum_value1=np.sum(value_less_than_five)

index2=np.where(index>=5)[0]
value_five_or_more=score[index2]
sum_value2=np.sum(value_five_or_more)

sum_all=sum_value1+sum_value2

display(score_sum)
display(sum_all)

964

964

## ----------------- Hints-----------------

In [53]:
A=[[1,4,7],[2,5,8],[3,6,9]]
A_np=np.array(A)

In [52]:
A_np[0,0]+A_np[1,1]+A_np[2,2]

15

In [55]:
index3=np.where(index==5)[0]
display(index3)

array([ 6, 11])

In [58]:
for i in range(10):
    display(i+1)

1

2

3

4

5

6

7

8

9

10